import Head from 'next/head'
import { signOut } from "next-auth/react";
import Header from '../components/Header';

export default function Home() {
  return (
    <div>

      <Head>
        <title>Linkedin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <div className="text-3xl">next linkedin</div>
      <button onClick={signOut}>Sign out</button> */}
      <Header/>
    </div>
  )
}
